### ISSUE TITLE
Wrong indication of found elements related to selected Attributes

### ISSUE THREAD

**Issue by martenAdrian** [msg-systems/ui5-testrecorder#54]
I tried to create a full test on the testrecorder presentation. 

While selecting a title by attributes, i selected the type "sap.m.Title" and the attribute text "About Testing".

The found items remained by 4 items. only attaching an additional attributes refines this to 1 item.
Also changing from Action to Assertion Type the 4 Items come back. 

A small debugging showed that only the type is send to the injected code for the selection and the attribute is removed. 
This only happens while refetching matching items.

**Comment by claushunsen** [comment]
Unfortunately, I do not know on which page you have found this issue, therefore, I tried my best to reproduce the issue as I already worked on similar issues in PR #53. I was able to reproduce, at least, parts of the issue with the following steps. _But, I do not know whether this is the complete problem that you describe, so please re-check this!_

Steps to reproduce (a part of the problem?):
1. Go to <https://ui5.sap.com/#/api/sap.m>.
2. Start recording a new test for this site.
3. Select `ActionListItem` in the TreeList on the left side.
4. In the test-recorder window, provide a unique combination of attributes by selecting 'Binding: title' and save.
5. There are three attributes provided for filtering now, the panel titles are colored in green, but, still and erroneously, 325 items are found.

---------------------

> The found items remained by 4 items. only attaching an additional attributes refines this to 1 item.
> Also changing from Action to Assertion Type the 4 Items come back.
> 
> A small debugging showed that only the type is send to the injected code for the selection and the attribute is removed.
> This only happens while refetching matching items.

I do not think that the attribute is removed somehow, it is rather not added in the first place (see code below): the preview is updated _before_ adding the attribute filters.  After reworking the workflow in PR #50, this was likely an unknown side-effect as, in the old workflow, the items were retrieved again somewhere else so that the problem has not occurred.
https://github.com/msg-systems/ui5-testrecorder/blob/cf4204dd4eb947cd08ab98aafada8cb94ecff4cd/scripts/popup/controller/TestStep.controller.js#L1727-L1747

I tried the simple fix: Changing the order of events (add the attribute filters first, then update the preview) indeed has an immediate effect on the problem. I will push a fix to PR #53 for you to review.

----------------------

> Also changing from Action to Assertion Type the 4 Items come back.

This is potentially fixed by executing the needed preview update when updating the test-step type. A fix by means of the commit dac9b1b54e207253f7d53945aaa488524d98f469 is already pushed to PR #53. Please review it there.
